namespace DotA2Analysis
{
	class Heroes
	{
		public static Hero[] DotA2Heroes =
		{
			new Hero("Alchemist", HeroAttribute.Strength, HeroRole.Carry, HeroRole.Disabler),
			new Hero("Ancient Apparition", HeroAttribute.Intelligence, HeroRole.Disabler, HeroRole.Support),
			new Hero("Anti-Mage", HeroAttribute.Agility, HeroRole.Carry, HeroRole.Escape),
			new Hero("Axe", HeroAttribute.Strength, HeroRole.Disabler, HeroRole.Initiator, HeroRole.Jungler),
			new Hero("Bane", HeroAttribute.Intelligence, HeroRole.Disabler, HeroRole.Nuker, HeroRole.Support),
			new Hero("Batrider", HeroAttribute.Intelligence, HeroRole.Disabler, HeroRole.Escape, HeroRole.Initiator, HeroRole.Nuker),
			new Hero("Beastmaster", HeroAttribute.Strength, HeroRole.Disabler, HeroRole.Initiator),
			new Hero("Bloodseeker", HeroAttribute.Agility, HeroRole.Carry, HeroRole.Jungler),
			new Hero("Bounty Hunter", HeroAttribute.Agility, HeroRole.Carry, HeroRole.Escape, HeroRole.Nuker),
			new Hero("Brewmaster", HeroAttribute.Strength, HeroRole.Carry, HeroRole.Initiator, HeroRole.Pusher),
			new Hero("Broodmother", HeroAttribute.Agility, HeroRole.Carry, HeroRole.Escape, HeroRole.Pusher),
			new Hero("Chaos Knight", HeroAttribute.Strength, HeroRole.Carry, HeroRole.Disabler, HeroRole.Pusher),
			new Hero("Chen", HeroAttribute.Intelligence, HeroRole.Jungler, HeroRole.Pusher, HeroRole.Support),
			new Hero("Clinkz", HeroAttribute.Agility, HeroRole.Carry, HeroRole.Escape),
			new Hero("Clockwerk", HeroAttribute.Strength, HeroRole.Initiator),
			new Hero("Crystal Maiden", HeroAttribute.Intelligence, HeroRole.Disabler, HeroRole.Nuker, HeroRole.LaneSupport, HeroRole.Support),
			new Hero("Dark Seer", HeroAttribute.Intelligence, HeroRole.Escape, HeroRole.Initiator, HeroRole.Nuker),
			new Hero("Dazzle", HeroAttribute.Intelligence, HeroRole.LaneSupport, HeroRole.Support),
			new Hero("Death Prophet", HeroAttribute.Intelligence, HeroRole.Nuker, HeroRole.Pusher),
			new Hero("Disruptor", HeroAttribute.Intelligence, HeroRole.Disabler, HeroRole.Initiator, HeroRole.Nuker, HeroRole.Support),
			new Hero("Doom Bringer", HeroAttribute.Strength, HeroRole.Carry, HeroRole.Nuker),
			new Hero("Dragon Knight", HeroAttribute.Strength, HeroRole.Carry, HeroRole.Disabler, HeroRole.Pusher),
			new Hero("Drow Ranger", HeroAttribute.Agility, HeroRole.Carry),
			new Hero("Earthshaker", HeroAttribute.Strength, HeroRole.Disabler, HeroRole.Initiator, HeroRole.LaneSupport, HeroRole.Support),
			new Hero("Enchantress", HeroAttribute.Intelligence, HeroRole.Jungler, HeroRole.Pusher, HeroRole.Support),
			new Hero("Enigma", HeroAttribute.Intelligence, HeroRole.Disabler, HeroRole.Initiator, HeroRole.Jungler, HeroRole.Pusher),
			new Hero("Faceless Void", HeroAttribute.Agility, HeroRole.Carry, HeroRole.Disabler, HeroRole.Escape, HeroRole.Initiator),
			new Hero("Gyrocopter", HeroAttribute.Agility, HeroRole.Disabler, HeroRole.Initiator, HeroRole.Nuker),
			new Hero("Huskar", HeroAttribute.Strength, HeroRole.Carry, HeroRole.Initiator),
			new Hero("Invoker", HeroAttribute.Intelligence, HeroRole.Carry, HeroRole.Escape, HeroRole.Initiator, HeroRole.Nuker),
			new Hero("Jakiro", HeroAttribute.Intelligence, HeroRole.Disabler, HeroRole.Nuker, HeroRole.LaneSupport, HeroRole.Pusher),
			new Hero("Juggernaut", HeroAttribute.Agility, HeroRole.Carry, HeroRole.Pusher),
			new Hero("Keeper of the Light", HeroAttribute.Intelligence, HeroRole.Pusher),
			new Hero("Kunkka", HeroAttribute.Strength, HeroRole.Carry, HeroRole.Disabler, HeroRole.Initiator),
			new Hero("Leshrac", HeroAttribute.Intelligence, HeroRole.Disabler, HeroRole.Nuker, HeroRole.Pusher, HeroRole.Support),
			new Hero("Lich", HeroAttribute.Intelligence, HeroRole.Nuker, HeroRole.LaneSupport, HeroRole.Support),
			new Hero("Lifestealer", HeroAttribute.Strength, HeroRole.Carry, HeroRole.Escape, HeroRole.Jungler),
			new Hero("Lina", HeroAttribute.Intelligence, HeroRole.Disabler, HeroRole.Nuker, HeroRole.Support),
			new Hero("Lion", HeroAttribute.Intelligence, HeroRole.Disabler, HeroRole.Nuker, HeroRole.LaneSupport, HeroRole.Support),
			new Hero("Lone Druid", HeroAttribute.Agility, HeroRole.Carry, HeroRole.Jungler, HeroRole.Pusher),
			new Hero("Luna", HeroAttribute.Agility, HeroRole.Carry, HeroRole.Nuker),
			new Hero("Lycanthrope", HeroAttribute.Strength, HeroRole.Carry, HeroRole.Jungler, HeroRole.Pusher),
			new Hero("Magnataur", HeroAttribute.Strength, HeroRole.Carry),
			new Hero("Meepo", HeroAttribute.Agility, HeroRole.Carry, HeroRole.Disabler, HeroRole.Initiator),
			new Hero("Mirana", HeroAttribute.Agility, HeroRole.Carry, HeroRole.Disabler, HeroRole.Escape, HeroRole.Nuker),
			new Hero("Morphling", HeroAttribute.Agility, HeroRole.Carry, HeroRole.Escape, HeroRole.Initiator, HeroRole.Nuker),
			new Hero("Naga Siren", HeroAttribute.Agility, HeroRole.Carry, HeroRole.Disabler, HeroRole.Escape, HeroRole.Pusher),
			new Hero("Nature's Prophet", HeroAttribute.Intelligence, HeroRole.Carry, HeroRole.Escape, HeroRole.Jungler, HeroRole.Pusher),
			new Hero("Necrolyte", HeroAttribute.Intelligence, HeroRole.Carry, HeroRole.Support),
			new Hero("Night Stalker", HeroAttribute.Strength, HeroRole.Initiator),
			new Hero("Nyx Assassin", HeroAttribute.Agility, HeroRole.Disabler, HeroRole.Nuker),
			new Hero("Ogre Magi", HeroAttribute.Intelligence, HeroRole.Disabler, HeroRole.Nuker),
			new Hero("Omniknight", HeroAttribute.Strength, HeroRole.LaneSupport, HeroRole.Support),
			new Hero("Outworld Destroyer", HeroAttribute.Intelligence, HeroRole.Carry),
			new Hero("Phantom Assassin", HeroAttribute.Agility, HeroRole.Carry, HeroRole.Escape),
			new Hero("Phantom Lancer", HeroAttribute.Agility, HeroRole.Carry, HeroRole.Escape, HeroRole.Pusher),
			new Hero("Puck", HeroAttribute.Intelligence, HeroRole.Disabler, HeroRole.Escape, HeroRole.Initiator, HeroRole.Nuker),
			new Hero("Pudge", HeroAttribute.Strength, HeroRole.Disabler),
			new Hero("Pugna", HeroAttribute.Intelligence, HeroRole.Nuker, HeroRole.Pusher, HeroRole.Support),
			new Hero("Queen of Pain", HeroAttribute.Intelligence, HeroRole.Carry, HeroRole.Escape, HeroRole.Nuker),
			new Hero("Razor", HeroAttribute.Agility, HeroRole.Carry, HeroRole.Nuker),
			new Hero("Riki", HeroAttribute.Agility, HeroRole.Carry, HeroRole.Escape),
			new Hero("Rubick", HeroAttribute.Intelligence, HeroRole.Disabler, HeroRole.Pusher),
			new Hero("Sand King", HeroAttribute.Strength, HeroRole.Disabler, HeroRole.Initiator, HeroRole.Nuker),
			new Hero("Shadow Demon", HeroAttribute.Intelligence, HeroRole.Disabler, HeroRole.Nuker, HeroRole.Support),
			new Hero("Shadow Fiend", HeroAttribute.Agility, HeroRole.Carry, HeroRole.Nuker),
			new Hero("Shadow Shaman", HeroAttribute.Intelligence, HeroRole.Disabler, HeroRole.Nuker, HeroRole.Pusher, HeroRole.Support),
			new Hero("Silencer", HeroAttribute.Intelligence, HeroRole.Carry, HeroRole.Initiator, HeroRole.Support),
			new Hero("Skeleton King", HeroAttribute.Strength, HeroRole.Carry, HeroRole.Disabler),
			new Hero("Slardar", HeroAttribute.Strength, HeroRole.Carry, HeroRole.Disabler, HeroRole.Initiator),
			new Hero("Sniper", HeroAttribute.Agility, HeroRole.Carry),
			new Hero("Spectre", HeroAttribute.Agility, HeroRole.Carry),
			new Hero("Spirit Breaker", HeroAttribute.Strength, HeroRole.Carry, HeroRole.Disabler, HeroRole.Initiator),
			new Hero("Storm Spirit", HeroAttribute.Intelligence, HeroRole.Carry, HeroRole.Disabler, HeroRole.Escape, HeroRole.Initiator),
			new Hero("Sven", HeroAttribute.Strength, HeroRole.Carry, HeroRole.Disabler, HeroRole.Initiator, HeroRole.Support),
			new Hero("Templar Assassin", HeroAttribute.Agility, HeroRole.Carry, HeroRole.Escape),
			new Hero("Tidehunter", HeroAttribute.Strength, HeroRole.Disabler, HeroRole.Initiator, HeroRole.Support),
			new Hero("Tinker", HeroAttribute.Intelligence, HeroRole.Nuker, HeroRole.Pusher),
			new Hero("Tiny", HeroAttribute.Strength, HeroRole.Disabler, HeroRole.Initiator, HeroRole.Nuker),
			new Hero("Treant Protector", HeroAttribute.Strength, HeroRole.Disabler, HeroRole.Initiator, HeroRole.LaneSupport),
			new Hero("Undying", HeroAttribute.Strength, HeroRole.Disabler, HeroRole.Initiator, HeroRole.Pusher),
			new Hero("Ursa", HeroAttribute.Agility, HeroRole.Carry, HeroRole.Jungler),
			new Hero("Vengeful Spirit", HeroAttribute.Agility, HeroRole.Disabler, HeroRole.Initiator, HeroRole.LaneSupport, HeroRole.Support),
			new Hero("Venomancer", HeroAttribute.Agility, HeroRole.Initiator, HeroRole.Nuker, HeroRole.Pusher, HeroRole.Support),
			new Hero("Viper", HeroAttribute.Agility, HeroRole.Carry),
			new Hero("Visage", HeroAttribute.Intelligence, HeroRole.Support),
			new Hero("Warlock", HeroAttribute.Intelligence, HeroRole.Disabler, HeroRole.Initiator, HeroRole.LaneSupport, HeroRole.Support),
			new Hero("Weaver", HeroAttribute.Agility, HeroRole.Carry, HeroRole.Escape),
			new Hero("Windrunner", HeroAttribute.Intelligence, HeroRole.Disabler, HeroRole.Escape, HeroRole.Nuker, HeroRole.Support),
			new Hero("Wisp", HeroAttribute.Strength, HeroRole.Support),
			new Hero("Witch Doctor", HeroAttribute.Intelligence, HeroRole.Disabler, HeroRole.Support),
			new Hero("Zeus", HeroAttribute.Intelligence, HeroRole.Nuker, HeroRole.Support),
		};
	}
}
